version: "3.9"

services:
  web_users_tests:
    build: .
    env_file:
      - .env.tests
    restart: "no"
    command: python manage.py runserver
    depends_on:
      redis:
        condition: service_healthy
  redis:
    restart: always
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    image: redis:7.0.5-alpine
    expose:
      - 6379
    env_file:
      - .env.tests
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
